// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4858.Spuds3;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.sensors.PigeonIMU;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX subSystemPIDDriveTrainLeftTalonSRX;
    public static WPI_TalonSRX subSystemPIDDriveTrainRightTalonSRX;
    public static WPI_TalonSRX subSystemPIDDriveTrainPidgeonTalonSRX;
    public static DifferentialDrive subSystemPIDDriveTrainRobotDrive;
    public static Encoder subSystemPIDDriveTrainQuadratureEncoder1;
    public static PigeonIMU subSystemPIDDriveTrainPigeonIMU1;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        subSystemPIDDriveTrainLeftTalonSRX = new WPI_TalonSRX(2);     
        subSystemPIDDriveTrainRightTalonSRX = new WPI_TalonSRX(5);  
        subSystemPIDDriveTrainRobotDrive = new DifferentialDrive(subSystemPIDDriveTrainLeftTalonSRX, subSystemPIDDriveTrainRightTalonSRX);
 
        LiveWindow.addActuator("SubSystemPIDDriveTrain", "Robot Drive", subSystemPIDDriveTrainRobotDrive);

        subSystemPIDDriveTrainRobotDrive.setSafetyEnabled(true);
        subSystemPIDDriveTrainRobotDrive.setExpiration(0.1);
        subSystemPIDDriveTrainRobotDrive.setMaxOutput(1.0);

        subSystemPIDDriveTrainQuadratureEncoder1 = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("SubSystemPIDDriveTrain", "Quadrature Encoder 1", subSystemPIDDriveTrainQuadratureEncoder1);
        subSystemPIDDriveTrainQuadratureEncoder1.setDistancePerPulse(1.0);
        subSystemPIDDriveTrainQuadratureEncoder1.setPIDSourceType(PIDSourceType.kRate);
        subSystemPIDDriveTrainPigeonIMU1 = new PigeonIMU(6);
        
        
        //subSystemPIDDriveTrainPidgeonTalonSRX = new WPI_TalonSRX(6);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
